// Code generated by protoc-gen-go.
// source: github.com/openconfig/reference/rpc/gnmi/gnmi.proto
// DO NOT EDIT!

/*
Package gnmi is a generated protocol buffer package.

Package gNMI defines a service specification for the gRPC Network Management
Interface. This interface is defined to be a standard interface via which
a network management system ("client") can subscribe to state values,
retrieve snapshots of state information, and manipulate the state of a data
tree supported by a device ("target").

This document references the gNMI Specification which can be found at
http://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi.md

It is generated from these files:
	github.com/openconfig/reference/rpc/gnmi/gnmi.proto

It has these top-level messages:
	Notification
	Update
	Path
	Value
	Error
	SubscribeRequest
	Poll
	SubscribeResponse
	SubscriptionList
	Subscription
	QOSMarking
	Alias
	AliasList
	SetRequest
	SetResponse
	UpdateResult
	GetRequest
	GetResponse
	CapabilityRequest
	CapabilityResponse
	ModelData
*/
package gnmi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"
import google_protobuf1 "github.com/golang/protobuf/protoc-gen-go/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Encoding defines the value encoding formats that are supported by the gNMI
// protocol. These encodings are used by both the client (when sending Set
// messages to modify the state of the target) and the target when serializing
// data to be returned to the client (in both Subscribe and Get RPCs).
// Reference: gNMI Specification Section 2.3
type Encoding int32

const (
	Encoding_JSON      Encoding = 0
	Encoding_BYTES     Encoding = 1
	Encoding_PROTO     Encoding = 2
	Encoding_JSON_IETF Encoding = 3
	Encoding_ASCII     Encoding = 4
)

var Encoding_name = map[int32]string{
	0: "JSON",
	1: "BYTES",
	2: "PROTO",
	3: "JSON_IETF",
	4: "ASCII",
}
var Encoding_value = map[string]int32{
	"JSON":      0,
	"BYTES":     1,
	"PROTO":     2,
	"JSON_IETF": 3,
	"ASCII":     4,
}

func (x Encoding) String() string {
	return proto.EnumName(Encoding_name, int32(x))
}
func (Encoding) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// SubscriptionMode is the mode of the subscription, specifying how the
// target must return values in a subscription.
// Reference: gNMI Specification Section 3.5.1.3
type SubscriptionMode int32

const (
	SubscriptionMode_TARGET_DEFINED SubscriptionMode = 0
	SubscriptionMode_ON_CHANGE      SubscriptionMode = 1
	SubscriptionMode_SAMPLE         SubscriptionMode = 2
)

var SubscriptionMode_name = map[int32]string{
	0: "TARGET_DEFINED",
	1: "ON_CHANGE",
	2: "SAMPLE",
}
var SubscriptionMode_value = map[string]int32{
	"TARGET_DEFINED": 0,
	"ON_CHANGE":      1,
	"SAMPLE":         2,
}

func (x SubscriptionMode) String() string {
	return proto.EnumName(SubscriptionMode_name, int32(x))
}
func (SubscriptionMode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// Mode of the subscription.
type SubscriptionList_Mode int32

const (
	SubscriptionList_STREAM SubscriptionList_Mode = 0
	SubscriptionList_ONCE   SubscriptionList_Mode = 1
	SubscriptionList_POLL   SubscriptionList_Mode = 2
)

var SubscriptionList_Mode_name = map[int32]string{
	0: "STREAM",
	1: "ONCE",
	2: "POLL",
}
var SubscriptionList_Mode_value = map[string]int32{
	"STREAM": 0,
	"ONCE":   1,
	"POLL":   2,
}

func (x SubscriptionList_Mode) String() string {
	return proto.EnumName(SubscriptionList_Mode_name, int32(x))
}
func (SubscriptionList_Mode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{8, 0} }

// The operation that was associated with the Path specified.
type UpdateResult_Operation int32

const (
	UpdateResult_INVALID UpdateResult_Operation = 0
	UpdateResult_DELETE  UpdateResult_Operation = 1
	UpdateResult_REPLACE UpdateResult_Operation = 2
	UpdateResult_UPDATE  UpdateResult_Operation = 3
)

var UpdateResult_Operation_name = map[int32]string{
	0: "INVALID",
	1: "DELETE",
	2: "REPLACE",
	3: "UPDATE",
}
var UpdateResult_Operation_value = map[string]int32{
	"INVALID": 0,
	"DELETE":  1,
	"REPLACE": 2,
	"UPDATE":  3,
}

func (x UpdateResult_Operation) String() string {
	return proto.EnumName(UpdateResult_Operation_name, int32(x))
}
func (UpdateResult_Operation) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{15, 0} }

// Type of elements within the data tree.
type GetRequest_DataType int32

const (
	GetRequest_ALL    GetRequest_DataType = 0
	GetRequest_CONFIG GetRequest_DataType = 1
	GetRequest_STATE  GetRequest_DataType = 2
	// Data elements marked in the schema as operational. This refers to data
	// elements whose value relates to the state of processes or interactions
	// running on the device.
	GetRequest_OPERATIONAL GetRequest_DataType = 3
)

var GetRequest_DataType_name = map[int32]string{
	0: "ALL",
	1: "CONFIG",
	2: "STATE",
	3: "OPERATIONAL",
}
var GetRequest_DataType_value = map[string]int32{
	"ALL":         0,
	"CONFIG":      1,
	"STATE":       2,
	"OPERATIONAL": 3,
}

func (x GetRequest_DataType) String() string {
	return proto.EnumName(GetRequest_DataType_name, int32(x))
}
func (GetRequest_DataType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{16, 0} }

// Notification is a re-usable message that is used to encode data from the
// target to the client. A Notification carries two types of changes to the data
// tree:
//  - Deleted values (delete) - a set of paths that have been removed from the
//    data tree.
//  - Updated values (update) - a set of path-value pairs indicating the path
//    whose value has changed in the data tree.
// Reference: gNMI Specification Section 2.1
type Notification struct {
	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Prefix    *Path `protobuf:"bytes,2,opt,name=prefix" json:"prefix,omitempty"`
	// An alias for the path specified in the prefix field.
	// Reference: gNMI Specification Section 2.4.2
	Alias  string    `protobuf:"bytes,3,opt,name=alias" json:"alias,omitempty"`
	Update []*Update `protobuf:"bytes,4,rep,name=update" json:"update,omitempty"`
	Delete []*Path   `protobuf:"bytes,5,rep,name=delete" json:"delete,omitempty"`
}

func (m *Notification) Reset()                    { *m = Notification{} }
func (m *Notification) String() string            { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()               {}
func (*Notification) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Notification) GetPrefix() *Path {
	if m != nil {
		return m.Prefix
	}
	return nil
}

func (m *Notification) GetUpdate() []*Update {
	if m != nil {
		return m.Update
	}
	return nil
}

func (m *Notification) GetDelete() []*Path {
	if m != nil {
		return m.Delete
	}
	return nil
}

// Update is a re-usable message that is used to store a particular Path,
// Value pair.
// Reference: gNMI Specification Section 2.1
type Update struct {
	Path  *Path  `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Value *Value `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *Update) Reset()                    { *m = Update{} }
func (m *Update) String() string            { return proto.CompactTextString(m) }
func (*Update) ProtoMessage()               {}
func (*Update) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Update) GetPath() *Path {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *Update) GetValue() *Value {
	if m != nil {
		return m.Value
	}
	return nil
}

// Path encodes a data tree path as a series of repeated strings, with
// each element of the path representing a data tree node name and the
// associated attributes.
// Reference: gNMI Specification Section 2.2.2.
type Path struct {
	Element []string `protobuf:"bytes,1,rep,name=element" json:"element,omitempty"`
	Origin  string   `protobuf:"bytes,2,opt,name=origin" json:"origin,omitempty"`
}

func (m *Path) Reset()                    { *m = Path{} }
func (m *Path) String() string            { return proto.CompactTextString(m) }
func (*Path) ProtoMessage()               {}
func (*Path) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// Value encodes a data tree node's value - along with the way in which
// the value is encoded.
// Reference: gNMI Specification Section 2.2.3.
type Value struct {
	Value []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Type  Encoding `protobuf:"varint,2,opt,name=type,enum=gnmi.Encoding" json:"type,omitempty"`
}

func (m *Value) Reset()                    { *m = Value{} }
func (m *Value) String() string            { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()               {}
func (*Value) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// Error message used by the target to return errors to the client.
// Reference: gNMI Specification Section 2.5
type Error struct {
	Code    uint32               `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Message string               `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Data    *google_protobuf.Any `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Error) GetData() *google_protobuf.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

// SubscribeRequest is the message sent by the client to the target when
// initiating a subscription to a set of paths within the data tree. The
// request field must be populated and the initial message must specify a
// SubscriptionList to initiate a subscription. The message is subsequently
// used to define aliases or trigger polled data to be sent by the target.
// Reference: gNMI Specification Section 3.5.1.1
type SubscribeRequest struct {
	// Types that are valid to be assigned to Request:
	//	*SubscribeRequest_Subscribe
	//	*SubscribeRequest_Poll
	//	*SubscribeRequest_Aliases
	Request isSubscribeRequest_Request `protobuf_oneof:"request"`
}

func (m *SubscribeRequest) Reset()                    { *m = SubscribeRequest{} }
func (m *SubscribeRequest) String() string            { return proto.CompactTextString(m) }
func (*SubscribeRequest) ProtoMessage()               {}
func (*SubscribeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type isSubscribeRequest_Request interface {
	isSubscribeRequest_Request()
}

type SubscribeRequest_Subscribe struct {
	Subscribe *SubscriptionList `protobuf:"bytes,1,opt,name=subscribe,oneof"`
}
type SubscribeRequest_Poll struct {
	Poll *Poll `protobuf:"bytes,3,opt,name=poll,oneof"`
}
type SubscribeRequest_Aliases struct {
	Aliases *AliasList `protobuf:"bytes,4,opt,name=aliases,oneof"`
}

func (*SubscribeRequest_Subscribe) isSubscribeRequest_Request() {}
func (*SubscribeRequest_Poll) isSubscribeRequest_Request()      {}
func (*SubscribeRequest_Aliases) isSubscribeRequest_Request()   {}

func (m *SubscribeRequest) GetRequest() isSubscribeRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *SubscribeRequest) GetSubscribe() *SubscriptionList {
	if x, ok := m.GetRequest().(*SubscribeRequest_Subscribe); ok {
		return x.Subscribe
	}
	return nil
}

func (m *SubscribeRequest) GetPoll() *Poll {
	if x, ok := m.GetRequest().(*SubscribeRequest_Poll); ok {
		return x.Poll
	}
	return nil
}

func (m *SubscribeRequest) GetAliases() *AliasList {
	if x, ok := m.GetRequest().(*SubscribeRequest_Aliases); ok {
		return x.Aliases
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*SubscribeRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _SubscribeRequest_OneofMarshaler, _SubscribeRequest_OneofUnmarshaler, _SubscribeRequest_OneofSizer, []interface{}{
		(*SubscribeRequest_Subscribe)(nil),
		(*SubscribeRequest_Poll)(nil),
		(*SubscribeRequest_Aliases)(nil),
	}
}

func _SubscribeRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*SubscribeRequest)
	// request
	switch x := m.Request.(type) {
	case *SubscribeRequest_Subscribe:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Subscribe); err != nil {
			return err
		}
	case *SubscribeRequest_Poll:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Poll); err != nil {
			return err
		}
	case *SubscribeRequest_Aliases:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Aliases); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("SubscribeRequest.Request has unexpected type %T", x)
	}
	return nil
}

func _SubscribeRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*SubscribeRequest)
	switch tag {
	case 1: // request.subscribe
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SubscriptionList)
		err := b.DecodeMessage(msg)
		m.Request = &SubscribeRequest_Subscribe{msg}
		return true, err
	case 3: // request.poll
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Poll)
		err := b.DecodeMessage(msg)
		m.Request = &SubscribeRequest_Poll{msg}
		return true, err
	case 4: // request.aliases
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(AliasList)
		err := b.DecodeMessage(msg)
		m.Request = &SubscribeRequest_Aliases{msg}
		return true, err
	default:
		return false, nil
	}
}

func _SubscribeRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*SubscribeRequest)
	// request
	switch x := m.Request.(type) {
	case *SubscribeRequest_Subscribe:
		s := proto.Size(x.Subscribe)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *SubscribeRequest_Poll:
		s := proto.Size(x.Poll)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *SubscribeRequest_Aliases:
		s := proto.Size(x.Aliases)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Poll is sent within a SubscribeRequest to trigger the device to
// send telemetry updates for the paths that are associated with the
// subscription.
// Reference: gNMI Specification Section Section 3.5.1.4
type Poll struct {
}

func (m *Poll) Reset()                    { *m = Poll{} }
func (m *Poll) String() string            { return proto.CompactTextString(m) }
func (*Poll) ProtoMessage()               {}
func (*Poll) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

// SubscribeResponse is the message used by the target within a Subscribe RPC.
// The target includes a Notification message which is used to transmit values
// of the path(s) that are associated with the subscription. The same message
// is to indicate that the target has sent all data values once (is
// synchronized). The error field is used to report errors that occur during
// creation of a subscription.
// Reference: gNMI Specification Section 3.5.1.4
type SubscribeResponse struct {
	// Types that are valid to be assigned to Response:
	//	*SubscribeResponse_Update
	//	*SubscribeResponse_SyncResponse
	//	*SubscribeResponse_Error
	Response isSubscribeResponse_Response `protobuf_oneof:"response"`
}

func (m *SubscribeResponse) Reset()                    { *m = SubscribeResponse{} }
func (m *SubscribeResponse) String() string            { return proto.CompactTextString(m) }
func (*SubscribeResponse) ProtoMessage()               {}
func (*SubscribeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type isSubscribeResponse_Response interface {
	isSubscribeResponse_Response()
}

type SubscribeResponse_Update struct {
	Update *Notification `protobuf:"bytes,1,opt,name=update,oneof"`
}
type SubscribeResponse_SyncResponse struct {
	SyncResponse bool `protobuf:"varint,3,opt,name=sync_response,json=syncResponse,oneof"`
}
type SubscribeResponse_Error struct {
	Error *Error `protobuf:"bytes,4,opt,name=error,oneof"`
}

func (*SubscribeResponse_Update) isSubscribeResponse_Response()       {}
func (*SubscribeResponse_SyncResponse) isSubscribeResponse_Response() {}
func (*SubscribeResponse_Error) isSubscribeResponse_Response()        {}

func (m *SubscribeResponse) GetResponse() isSubscribeResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *SubscribeResponse) GetUpdate() *Notification {
	if x, ok := m.GetResponse().(*SubscribeResponse_Update); ok {
		return x.Update
	}
	return nil
}

func (m *SubscribeResponse) GetSyncResponse() bool {
	if x, ok := m.GetResponse().(*SubscribeResponse_SyncResponse); ok {
		return x.SyncResponse
	}
	return false
}

func (m *SubscribeResponse) GetError() *Error {
	if x, ok := m.GetResponse().(*SubscribeResponse_Error); ok {
		return x.Error
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*SubscribeResponse) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _SubscribeResponse_OneofMarshaler, _SubscribeResponse_OneofUnmarshaler, _SubscribeResponse_OneofSizer, []interface{}{
		(*SubscribeResponse_Update)(nil),
		(*SubscribeResponse_SyncResponse)(nil),
		(*SubscribeResponse_Error)(nil),
	}
}

func _SubscribeResponse_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*SubscribeResponse)
	// response
	switch x := m.Response.(type) {
	case *SubscribeResponse_Update:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Update); err != nil {
			return err
		}
	case *SubscribeResponse_SyncResponse:
		t := uint64(0)
		if x.SyncResponse {
			t = 1
		}
		b.EncodeVarint(3<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case *SubscribeResponse_Error:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Error); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("SubscribeResponse.Response has unexpected type %T", x)
	}
	return nil
}

func _SubscribeResponse_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*SubscribeResponse)
	switch tag {
	case 1: // response.update
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Notification)
		err := b.DecodeMessage(msg)
		m.Response = &SubscribeResponse_Update{msg}
		return true, err
	case 3: // response.sync_response
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Response = &SubscribeResponse_SyncResponse{x != 0}
		return true, err
	case 4: // response.error
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Error)
		err := b.DecodeMessage(msg)
		m.Response = &SubscribeResponse_Error{msg}
		return true, err
	default:
		return false, nil
	}
}

func _SubscribeResponse_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*SubscribeResponse)
	// response
	switch x := m.Response.(type) {
	case *SubscribeResponse_Update:
		s := proto.Size(x.Update)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *SubscribeResponse_SyncResponse:
		n += proto.SizeVarint(3<<3 | proto.WireVarint)
		n += 1
	case *SubscribeResponse_Error:
		s := proto.Size(x.Error)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// SubscriptionList is used within a Subscribe message to specify the list of
// paths that the client wishes to subscribe to. The message consists of a
// list of (possibly prefixed) paths, and options that relate to the
// subscription.
// Reference: gNMI Specification Section 3.5.1.2
type SubscriptionList struct {
	Prefix       *Path           `protobuf:"bytes,1,opt,name=prefix" json:"prefix,omitempty"`
	Subscription []*Subscription `protobuf:"bytes,2,rep,name=subscription" json:"subscription,omitempty"`
	// Whether target defined aliases are allowed within the subscription.
	UseAliases bool                  `protobuf:"varint,3,opt,name=use_aliases,json=useAliases" json:"use_aliases,omitempty"`
	Qos        *QOSMarking           `protobuf:"bytes,4,opt,name=qos" json:"qos,omitempty"`
	Mode       SubscriptionList_Mode `protobuf:"varint,5,opt,name=mode,enum=gnmi.SubscriptionList_Mode" json:"mode,omitempty"`
	// Whether elements of the schema that are marked as eligible for aggregation
	// should be aggregated or not.
	AllowAggregation bool `protobuf:"varint,6,opt,name=allow_aggregation,json=allowAggregation" json:"allow_aggregation,omitempty"`
	// The set of schemas that define the elements of the data tree that should
	// be sent by the target.
	UseModels []*ModelData `protobuf:"bytes,7,rep,name=use_models,json=useModels" json:"use_models,omitempty"`
}

func (m *SubscriptionList) Reset()                    { *m = SubscriptionList{} }
func (m *SubscriptionList) String() string            { return proto.CompactTextString(m) }
func (*SubscriptionList) ProtoMessage()               {}
func (*SubscriptionList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *SubscriptionList) GetPrefix() *Path {
	if m != nil {
		return m.Prefix
	}
	return nil
}

func (m *SubscriptionList) GetSubscription() []*Subscription {
	if m != nil {
		return m.Subscription
	}
	return nil
}

func (m *SubscriptionList) GetQos() *QOSMarking {
	if m != nil {
		return m.Qos
	}
	return nil
}

func (m *SubscriptionList) GetUseModels() []*ModelData {
	if m != nil {
		return m.UseModels
	}
	return nil
}

// Subscription is a single request within a SubscriptionList. The path
// specified is interpreted (along with the prefix) as the elements of the data
// tree that the client is subscribing to. The mode determines how the target
// should trigger updates to be sent.
// Reference: gNMI Specification Section 3.5.1.3
type Subscription struct {
	Path           *Path            `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Mode           SubscriptionMode `protobuf:"varint,2,opt,name=mode,enum=gnmi.SubscriptionMode" json:"mode,omitempty"`
	SampleInterval uint64           `protobuf:"varint,3,opt,name=sample_interval,json=sampleInterval" json:"sample_interval,omitempty"`
	// Indicates whether values that not changed should be sent in a SAMPLE
	// subscription.
	SuppressRedundant bool `protobuf:"varint,4,opt,name=suppress_redundant,json=suppressRedundant" json:"suppress_redundant,omitempty"`
	// Specifies the maximum allowable silent period in nanoseconds when
	// suppress_redundant is in use. The target should send a value at least once
	// in the period specified.
	HeartbeatInterval uint64 `protobuf:"varint,5,opt,name=heartbeat_interval,json=heartbeatInterval" json:"heartbeat_interval,omitempty"`
}

func (m *Subscription) Reset()                    { *m = Subscription{} }
func (m *Subscription) String() string            { return proto.CompactTextString(m) }
func (*Subscription) ProtoMessage()               {}
func (*Subscription) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Subscription) GetPath() *Path {
	if m != nil {
		return m.Path
	}
	return nil
}

// QOSMarking specifies the DSCP value to be set on transmitted telemetry
// updates from the target.
// Reference: gNMI Specification Section 3.5.1.2
type QOSMarking struct {
	Marking uint32 `protobuf:"varint,1,opt,name=marking" json:"marking,omitempty"`
}

func (m *QOSMarking) Reset()                    { *m = QOSMarking{} }
func (m *QOSMarking) String() string            { return proto.CompactTextString(m) }
func (*QOSMarking) ProtoMessage()               {}
func (*QOSMarking) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

// Alias specifies a data tree path, and an associated string which defines an
// alias which is to be used for this path in the context of the RPC. The alias
// is specified as a string which is prefixed with "#" to disambiguate it from
// data tree element paths.
// Reference: gNMI Specification Section 2.4.2
type Alias struct {
	Path  *Path  `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Alias string `protobuf:"bytes,2,opt,name=alias" json:"alias,omitempty"`
}

func (m *Alias) Reset()                    { *m = Alias{} }
func (m *Alias) String() string            { return proto.CompactTextString(m) }
func (*Alias) ProtoMessage()               {}
func (*Alias) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *Alias) GetPath() *Path {
	if m != nil {
		return m.Path
	}
	return nil
}

// AliasList specifies a list of aliases. It is used in a SubscribeRequest for
// a client to create a set of aliases that the target is to utilize.
// Reference: gNMI Specification Section 3.5.1.6
type AliasList struct {
	Alias []*Alias `protobuf:"bytes,1,rep,name=alias" json:"alias,omitempty"`
}

func (m *AliasList) Reset()                    { *m = AliasList{} }
func (m *AliasList) String() string            { return proto.CompactTextString(m) }
func (*AliasList) ProtoMessage()               {}
func (*AliasList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *AliasList) GetAlias() []*Alias {
	if m != nil {
		return m.Alias
	}
	return nil
}

// SetRequest is sent from a client to the target to update values in the data
// tree. Paths are either deleted by the client, or modified by means of being
// updated, or replaced. Where a replace is used, unspecified values are
// considered to be replaced, whereas when update is used the changes are
// considered to be incremental. The set of changes that are specified within
// a single SetRequest are considered to be a transaction.
// Reference: gNMI Specification Section 3.4.1
type SetRequest struct {
	Prefix  *Path     `protobuf:"bytes,1,opt,name=prefix" json:"prefix,omitempty"`
	Delete  []*Path   `protobuf:"bytes,2,rep,name=delete" json:"delete,omitempty"`
	Replace []*Update `protobuf:"bytes,3,rep,name=replace" json:"replace,omitempty"`
	Update  []*Update `protobuf:"bytes,4,rep,name=update" json:"update,omitempty"`
}

func (m *SetRequest) Reset()                    { *m = SetRequest{} }
func (m *SetRequest) String() string            { return proto.CompactTextString(m) }
func (*SetRequest) ProtoMessage()               {}
func (*SetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *SetRequest) GetPrefix() *Path {
	if m != nil {
		return m.Prefix
	}
	return nil
}

func (m *SetRequest) GetDelete() []*Path {
	if m != nil {
		return m.Delete
	}
	return nil
}

func (m *SetRequest) GetReplace() []*Update {
	if m != nil {
		return m.Replace
	}
	return nil
}

func (m *SetRequest) GetUpdate() []*Update {
	if m != nil {
		return m.Update
	}
	return nil
}

// SetResponse is the response to a SetRequest, sent from the target to the
// client. It reports the result of the modifications to the data tree that were
// specified by the client.
// Reference: gNMI Specification Section 3.4.2
type SetResponse struct {
	Prefix *Path `protobuf:"bytes,1,opt,name=prefix" json:"prefix,omitempty"`
	// A set of responses specifying the result of the operations specified in
	// the SetRequest.
	Response []*UpdateResult `protobuf:"bytes,2,rep,name=response" json:"response,omitempty"`
	Message  *Error          `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *SetResponse) Reset()                    { *m = SetResponse{} }
func (m *SetResponse) String() string            { return proto.CompactTextString(m) }
func (*SetResponse) ProtoMessage()               {}
func (*SetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *SetResponse) GetPrefix() *Path {
	if m != nil {
		return m.Prefix
	}
	return nil
}

func (m *SetResponse) GetResponse() []*UpdateResult {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *SetResponse) GetMessage() *Error {
	if m != nil {
		return m.Message
	}
	return nil
}

// UpdateResult is used within the SetResponse message to communicate the
// result of an operation specified within a SetRequest message.
// Reference: gNMI Specification Section 3.4.2
type UpdateResult struct {
	Timestamp int64                  `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Path      *Path                  `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	Message   *Error                 `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	Op        UpdateResult_Operation `protobuf:"varint,4,opt,name=op,enum=gnmi.UpdateResult_Operation" json:"op,omitempty"`
}

func (m *UpdateResult) Reset()                    { *m = UpdateResult{} }
func (m *UpdateResult) String() string            { return proto.CompactTextString(m) }
func (*UpdateResult) ProtoMessage()               {}
func (*UpdateResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *UpdateResult) GetPath() *Path {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *UpdateResult) GetMessage() *Error {
	if m != nil {
		return m.Message
	}
	return nil
}

// GetRequest is sent when a client initiates a Get RPC. It is used to specify
// the set of data elements for which the target should return a snapshot of
// data. The use_models field specifies the set of schema modules that are to
// be used by the target - where use_models is not specified then the target
// must use all schema models that it has.
// Reference: gNMI Specification Section 3.3.1
type GetRequest struct {
	Prefix    *Path               `protobuf:"bytes,1,opt,name=prefix" json:"prefix,omitempty"`
	Path      []*Path             `protobuf:"bytes,2,rep,name=path" json:"path,omitempty"`
	Type      GetRequest_DataType `protobuf:"varint,3,opt,name=type,enum=gnmi.GetRequest_DataType" json:"type,omitempty"`
	Encoding  Encoding            `protobuf:"varint,5,opt,name=encoding,enum=gnmi.Encoding" json:"encoding,omitempty"`
	UseModels []*ModelData        `protobuf:"bytes,6,rep,name=use_models,json=useModels" json:"use_models,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *GetRequest) GetPrefix() *Path {
	if m != nil {
		return m.Prefix
	}
	return nil
}

func (m *GetRequest) GetPath() []*Path {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *GetRequest) GetUseModels() []*ModelData {
	if m != nil {
		return m.UseModels
	}
	return nil
}

// GetResponse is used by the target to respond to a GetRequest from a client.
// The set of Notifications corresponds to the data values that are requested
// by the client in the GetRequest.
// Reference: gNMI Specification Section 3.3.2
type GetResponse struct {
	Notification []*Notification `protobuf:"bytes,1,rep,name=notification" json:"notification,omitempty"`
	Error        *Error          `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *GetResponse) Reset()                    { *m = GetResponse{} }
func (m *GetResponse) String() string            { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()               {}
func (*GetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *GetResponse) GetNotification() []*Notification {
	if m != nil {
		return m.Notification
	}
	return nil
}

func (m *GetResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

// CapabilityRequest is sent by the client in the Capabilities RPC to request
// that the target reports its capabilities.
// Reference: gNMI Specification Section 3.2.1
type CapabilityRequest struct {
}

func (m *CapabilityRequest) Reset()                    { *m = CapabilityRequest{} }
func (m *CapabilityRequest) String() string            { return proto.CompactTextString(m) }
func (*CapabilityRequest) ProtoMessage()               {}
func (*CapabilityRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

// CapabilityResponse is used by the target to report its capabilities to the
// client within the Capabilities RPC.
// Reference: gNMI Specification Section 3.2.2
type CapabilityResponse struct {
	SupportedModels    []*ModelData `protobuf:"bytes,1,rep,name=supported_models,json=supportedModels" json:"supported_models,omitempty"`
	SupportedEncodings []Encoding   `protobuf:"varint,2,rep,packed,name=supported_encodings,json=supportedEncodings,enum=gnmi.Encoding" json:"supported_encodings,omitempty"`
	GNMIVersion        string       `protobuf:"bytes,3,opt,name=gNMI_version,json=gNMIVersion" json:"gNMI_version,omitempty"`
}

func (m *CapabilityResponse) Reset()                    { *m = CapabilityResponse{} }
func (m *CapabilityResponse) String() string            { return proto.CompactTextString(m) }
func (*CapabilityResponse) ProtoMessage()               {}
func (*CapabilityResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *CapabilityResponse) GetSupportedModels() []*ModelData {
	if m != nil {
		return m.SupportedModels
	}
	return nil
}

// ModelData is used to describe a set of schema modules. It can be used in a
// CapabilityResponse where a target reports the set of modules that it
// supports, and within the SubscribeRequest and GetRequest messages to specify
// the set of models from which data tree elements should be reported.
// Reference: gNMI Specification Section 3.2.3
type ModelData struct {
	Name         string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Organization string `protobuf:"bytes,2,opt,name=organization" json:"organization,omitempty"`
	Version      string `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
}

func (m *ModelData) Reset()                    { *m = ModelData{} }
func (m *ModelData) String() string            { return proto.CompactTextString(m) }
func (*ModelData) ProtoMessage()               {}
func (*ModelData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

var E_GnmiService = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf1.FileOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         1001,
	Name:          "gnmi.gnmi_service",
	Tag:           "bytes,1001,opt,name=gnmi_service,json=gnmiService",
}

func init() {
	proto.RegisterType((*Notification)(nil), "gnmi.Notification")
	proto.RegisterType((*Update)(nil), "gnmi.Update")
	proto.RegisterType((*Path)(nil), "gnmi.Path")
	proto.RegisterType((*Value)(nil), "gnmi.Value")
	proto.RegisterType((*Error)(nil), "gnmi.Error")
	proto.RegisterType((*SubscribeRequest)(nil), "gnmi.SubscribeRequest")
	proto.RegisterType((*Poll)(nil), "gnmi.Poll")
	proto.RegisterType((*SubscribeResponse)(nil), "gnmi.SubscribeResponse")
	proto.RegisterType((*SubscriptionList)(nil), "gnmi.SubscriptionList")
	proto.RegisterType((*Subscription)(nil), "gnmi.Subscription")
	proto.RegisterType((*QOSMarking)(nil), "gnmi.QOSMarking")
	proto.RegisterType((*Alias)(nil), "gnmi.Alias")
	proto.RegisterType((*AliasList)(nil), "gnmi.AliasList")
	proto.RegisterType((*SetRequest)(nil), "gnmi.SetRequest")
	proto.RegisterType((*SetResponse)(nil), "gnmi.SetResponse")
	proto.RegisterType((*UpdateResult)(nil), "gnmi.UpdateResult")
	proto.RegisterType((*GetRequest)(nil), "gnmi.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "gnmi.GetResponse")
	proto.RegisterType((*CapabilityRequest)(nil), "gnmi.CapabilityRequest")
	proto.RegisterType((*CapabilityResponse)(nil), "gnmi.CapabilityResponse")
	proto.RegisterType((*ModelData)(nil), "gnmi.ModelData")
	proto.RegisterEnum("gnmi.Encoding", Encoding_name, Encoding_value)
	proto.RegisterEnum("gnmi.SubscriptionMode", SubscriptionMode_name, SubscriptionMode_value)
	proto.RegisterEnum("gnmi.SubscriptionList_Mode", SubscriptionList_Mode_name, SubscriptionList_Mode_value)
	proto.RegisterEnum("gnmi.UpdateResult_Operation", UpdateResult_Operation_name, UpdateResult_Operation_value)
	proto.RegisterEnum("gnmi.GetRequest_DataType", GetRequest_DataType_name, GetRequest_DataType_value)
	proto.RegisterExtension(E_GnmiService)
}

func init() {
	proto.RegisterFile("github.com/openconfig/reference/rpc/gnmi/gnmi.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 1460 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x56, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0xf6, 0xae, 0xd7, 0x3f, 0x7b, 0xec, 0x24, 0x9b, 0x69, 0xd5, 0x9a, 0x50, 0x41, 0xba, 0xd0,
	0x12, 0xa5, 0xad, 0x5d, 0xa5, 0x52, 0x85, 0x8a, 0x4a, 0xbb, 0x49, 0x36, 0x89, 0xc1, 0xb1, 0xc3,
	0xd8, 0xad, 0xc4, 0x05, 0xb2, 0xc6, 0xf6, 0xc4, 0x59, 0xb1, 0xde, 0xdd, 0xee, 0xac, 0x03, 0xe1,
	0x09, 0x78, 0x04, 0xb8, 0x45, 0x3c, 0x00, 0x17, 0x3c, 0x05, 0x4f, 0x01, 0xe2, 0xaa, 0x6f, 0x81,
	0x66, 0x66, 0xff, 0x5c, 0xa7, 0x4a, 0xb8, 0xb0, 0x35, 0x73, 0xfe, 0xe6, 0x9c, 0xef, 0xfc, 0x2d,
	0x3c, 0x99, 0x3a, 0xd1, 0xd9, 0x7c, 0xd4, 0x1c, 0xfb, 0xb3, 0x96, 0x1f, 0x50, 0x6f, 0xec, 0x7b,
	0xa7, 0xce, 0xb4, 0x15, 0xd2, 0x53, 0x1a, 0x52, 0x6f, 0x4c, 0x5b, 0x61, 0x30, 0x6e, 0x4d, 0xbd,
	0x99, 0x23, 0xfe, 0x9a, 0x41, 0xe8, 0x47, 0x3e, 0xd2, 0xf8, 0x79, 0xa3, 0x95, 0x53, 0x9d, 0xfa,
	0x2e, 0xf1, 0xa6, 0x2d, 0xc1, 0x1e, 0xcd, 0x4f, 0x5b, 0x41, 0x74, 0x11, 0x50, 0xd6, 0x22, 0xde,
	0x05, 0xff, 0x49, 0xb5, 0x8d, 0x17, 0x0b, 0x0a, 0xfe, 0xd4, 0xa5, 0x99, 0x02, 0x0b, 0xc7, 0x4b,
	0xb4, 0x09, 0x65, 0xe3, 0xd0, 0x09, 0x22, 0x3f, 0x94, 0x06, 0xcc, 0x3f, 0x14, 0xa8, 0x77, 0xfd,
	0xc8, 0x39, 0x75, 0xc6, 0x24, 0x72, 0x7c, 0x0f, 0xdd, 0x01, 0x3d, 0x72, 0x66, 0x94, 0x45, 0x64,
	0x16, 0x34, 0x94, 0x4d, 0x65, 0xab, 0x88, 0x33, 0x02, 0x32, 0xa1, 0x1c, 0x84, 0xf4, 0xd4, 0xf9,
	0xb1, 0xa1, 0x6e, 0x2a, 0x5b, 0xb5, 0x1d, 0x68, 0x8a, 0x18, 0x4e, 0x48, 0x74, 0x86, 0x63, 0x0e,
	0xba, 0x09, 0x25, 0xe2, 0x3a, 0x84, 0x35, 0x8a, 0x9b, 0xca, 0x96, 0x8e, 0xe5, 0x05, 0x7d, 0x0a,
	0xe5, 0x79, 0x30, 0x21, 0x11, 0x6d, 0x68, 0x9b, 0xc5, 0xad, 0xda, 0x4e, 0x5d, 0x6a, 0xbe, 0x12,
	0x34, 0x1c, 0xf3, 0xb8, 0xfd, 0x09, 0x75, 0x69, 0x44, 0x1b, 0x25, 0x21, 0xb5, 0x60, 0x5f, 0x72,
	0xcc, 0xaf, 0xa1, 0x2c, 0xb5, 0xd0, 0x47, 0xa0, 0x05, 0x24, 0x3a, 0x13, 0x6e, 0x2e, 0xca, 0x0a,
	0x3a, 0xba, 0x0b, 0xa5, 0x73, 0xe2, 0xce, 0x69, 0xec, 0x6c, 0x4d, 0x0a, 0xbc, 0xe6, 0x24, 0x2c,
	0x39, 0xe6, 0xe7, 0xa0, 0x71, 0x05, 0xd4, 0x80, 0x0a, 0x75, 0xe9, 0x8c, 0x7a, 0x51, 0x43, 0xd9,
	0x2c, 0x6e, 0xe9, 0x38, 0xb9, 0xa2, 0x5b, 0x50, 0xf6, 0x43, 0x67, 0xea, 0x78, 0xc2, 0x8a, 0x8e,
	0xe3, 0x9b, 0x69, 0x41, 0x49, 0x58, 0xe2, 0xf1, 0xca, 0x57, 0xb8, 0x1b, 0xf5, 0xd8, 0x30, 0x32,
	0x41, 0xe3, 0x09, 0x13, 0x4a, 0xab, 0x3b, 0xab, 0xf2, 0x69, 0xdb, 0x1b, 0xfb, 0x13, 0xc7, 0x9b,
	0x62, 0xc1, 0x33, 0x87, 0x50, 0xb2, 0xc3, 0xd0, 0x0f, 0x11, 0x02, 0x6d, 0xec, 0x4f, 0xa4, 0x85,
	0x15, 0x2c, 0xce, 0xdc, 0xa3, 0x19, 0x65, 0x8c, 0x4c, 0x69, 0xfc, 0x70, 0x72, 0x45, 0x5b, 0xa0,
	0x4d, 0x48, 0x44, 0x04, 0xbe, 0xb5, 0x9d, 0x9b, 0x4d, 0x99, 0xe4, 0x66, 0x92, 0xe4, 0xa6, 0xe5,
	0x5d, 0x60, 0x21, 0x61, 0xfe, 0xae, 0x80, 0xd1, 0x9f, 0x8f, 0x78, 0xce, 0x47, 0x14, 0xd3, 0x37,
	0x73, 0xca, 0x22, 0xf4, 0x14, 0x74, 0x96, 0xd0, 0x62, 0xe8, 0x6e, 0x49, 0xf7, 0x62, 0xd1, 0x80,
	0x17, 0x42, 0xc7, 0x61, 0xd1, 0x51, 0x01, 0x67, 0xa2, 0x68, 0x13, 0xb4, 0xc0, 0x77, 0xdd, 0xf8,
	0xd9, 0x04, 0x6d, 0xdf, 0x75, 0x8f, 0x0a, 0x58, 0x70, 0xd0, 0x03, 0xa8, 0x88, 0x64, 0x53, 0xd6,
	0xd0, 0x84, 0xd0, 0x9a, 0x14, 0xb2, 0x38, 0x31, 0x36, 0x98, 0x48, 0xec, 0xea, 0x50, 0x09, 0xa5,
	0x47, 0x66, 0x19, 0x34, 0x6e, 0xc7, 0xfc, 0x55, 0x81, 0xf5, 0x9c, 0xbb, 0x2c, 0xf0, 0x3d, 0x46,
	0xd1, 0xc3, 0xb4, 0x72, 0xa4, 0xb3, 0x48, 0x1a, 0xcd, 0x57, 0xed, 0x51, 0x21, 0xad, 0xa0, 0x7b,
	0xb0, 0xc2, 0x2e, 0xbc, 0xf1, 0x30, 0x8c, 0xd5, 0x85, 0xbb, 0xd5, 0xa3, 0x02, 0xae, 0x73, 0x72,
	0x6a, 0xf4, 0x13, 0x28, 0x51, 0x0e, 0x7d, 0xec, 0x68, 0x5c, 0x1a, 0x22, 0x1b, 0x47, 0x05, 0x2c,
	0x79, 0xbb, 0x00, 0xd5, 0xc4, 0x8c, 0xf9, 0x56, 0x4d, 0xa1, 0x4c, 0xf1, 0xc9, 0xb5, 0x83, 0xf2,
	0xde, 0x76, 0x78, 0x0a, 0x75, 0x96, 0xd3, 0x6b, 0xa8, 0xa2, 0xb0, 0xd1, 0x32, 0xe2, 0x78, 0x41,
	0x0e, 0x7d, 0x0c, 0xb5, 0x39, 0xa3, 0xc3, 0x04, 0x50, 0x11, 0x06, 0x86, 0x39, 0xa3, 0x96, 0xa4,
	0x20, 0x13, 0x8a, 0x6f, 0xfc, 0x04, 0x69, 0x43, 0xda, 0xfb, 0xa6, 0xd7, 0x3f, 0x26, 0xe1, 0xf7,
	0xbc, 0xc4, 0x38, 0x13, 0xb5, 0x40, 0x9b, 0xf1, 0xc2, 0x2a, 0x89, 0x2a, 0xfc, 0xf0, 0xf2, 0x34,
	0x37, 0x8f, 0xfd, 0x09, 0xc5, 0x42, 0x10, 0x3d, 0x80, 0x75, 0xe2, 0xba, 0xfe, 0x0f, 0x43, 0x32,
	0x9d, 0x86, 0x74, 0x2a, 0xd0, 0x6d, 0x94, 0xc5, 0xdb, 0x86, 0x60, 0x58, 0x19, 0x1d, 0x35, 0x81,
	0xfb, 0x33, 0xe4, 0x8a, 0x2e, 0x6b, 0x54, 0x44, 0x60, 0x71, 0xca, 0xb9, 0x49, 0x77, 0x9f, 0x44,
	0x04, 0xeb, 0x73, 0x46, 0xc5, 0x8d, 0x99, 0xf7, 0x41, 0xe3, 0x27, 0x04, 0x50, 0xee, 0x0f, 0xb0,
	0x6d, 0x1d, 0x1b, 0x05, 0x54, 0x05, 0xad, 0xd7, 0xdd, 0xb3, 0x0d, 0x85, 0x9f, 0x4e, 0x7a, 0x9d,
	0x8e, 0xa1, 0x9a, 0xff, 0x28, 0x50, 0xcf, 0x3b, 0x79, 0x65, 0xa3, 0x6f, 0xc7, 0x61, 0xca, 0x66,
	0xbb, 0xa4, 0x9a, 0x73, 0x11, 0x7e, 0x06, 0x6b, 0x8c, 0xcc, 0x02, 0x97, 0x0e, 0x1d, 0x2f, 0xa2,
	0xe1, 0x39, 0x91, 0x15, 0xad, 0xe1, 0x55, 0x49, 0x6e, 0xc7, 0x54, 0xf4, 0x08, 0x10, 0x9b, 0x07,
	0x41, 0x48, 0x19, 0x1b, 0x86, 0x74, 0x32, 0xf7, 0x26, 0xc4, 0x8b, 0x04, 0xdc, 0x55, 0xbc, 0x9e,
	0x70, 0x70, 0xc2, 0xe0, 0xe2, 0x67, 0x94, 0x84, 0xd1, 0x88, 0x92, 0x28, 0x33, 0x5d, 0x12, 0xa6,
	0xd7, 0x53, 0x4e, 0x62, 0xdd, 0xbc, 0x0f, 0x90, 0x25, 0x4b, 0x34, 0xbb, 0x3c, 0xc6, 0x33, 0x20,
	0xb9, 0x9a, 0xcf, 0xa1, 0x24, 0x12, 0x7e, 0x25, 0x06, 0xe9, 0xd8, 0x55, 0x73, 0x63, 0xd7, 0x6c,
	0x82, 0x9e, 0x76, 0x1f, 0x9f, 0x87, 0x52, 0x44, 0x11, 0xa9, 0xaa, 0xe5, 0xba, 0x33, 0x91, 0xff,
	0x4d, 0x01, 0xe8, 0xd3, 0x28, 0x99, 0x15, 0xd7, 0x29, 0xf0, 0x6c, 0x66, 0xab, 0xef, 0x9b, 0xd9,
	0xe8, 0x3e, 0x6f, 0xf6, 0xc0, 0x25, 0x63, 0xde, 0x8f, 0xcb, 0xe3, 0x3f, 0x61, 0x5e, 0x6f, 0x4b,
	0x98, 0x3f, 0x2b, 0x50, 0x13, 0x4e, 0xc6, 0xcd, 0x7c, 0x1d, 0x2f, 0x9b, 0x59, 0x2f, 0x2f, 0xb6,
	0x60, 0x6c, 0x9b, 0xb2, 0xb9, 0x1b, 0xe1, 0x54, 0x06, 0xdd, 0xcb, 0xc6, 0x6f, 0x71, 0x69, 0x44,
	0xa4, 0xb3, 0xd8, 0xfc, 0x5b, 0x81, 0x7a, 0xde, 0xc2, 0x15, 0xfb, 0x33, 0x49, 0xa2, 0xfa, 0x9e,
	0x24, 0x5e, 0xef, 0x55, 0xf4, 0x10, 0x54, 0x3f, 0x10, 0xa5, 0xb8, 0xba, 0x73, 0x67, 0x39, 0x8c,
	0x66, 0x2f, 0xa0, 0xa1, 0x68, 0x51, 0xac, 0xfa, 0x81, 0xf9, 0x1c, 0xf4, 0x94, 0x80, 0x6a, 0x50,
	0x69, 0x77, 0x5f, 0x5b, 0x9d, 0xf6, 0xbe, 0x51, 0xe0, 0x8d, 0xb8, 0x6f, 0x77, 0xec, 0x01, 0x6f,
	0xbf, 0x1a, 0x54, 0xb0, 0x7d, 0xd2, 0xb1, 0xf6, 0x6c, 0x43, 0xe5, 0x8c, 0x57, 0x27, 0xfb, 0xd6,
	0xc0, 0x36, 0x8a, 0xe6, 0x2f, 0x2a, 0xc0, 0xe1, 0xff, 0x2b, 0x89, 0x2c, 0xcc, 0xe2, 0xa5, 0x61,
	0x3e, 0x8a, 0x97, 0x63, 0x51, 0x44, 0xf0, 0x81, 0xe4, 0x67, 0x6f, 0x34, 0xf9, 0xe0, 0x18, 0x5c,
	0x04, 0x54, 0xee, 0x49, 0xb4, 0x0d, 0x55, 0x1a, 0x6f, 0xce, 0x78, 0x92, 0xbd, 0xbb, 0x4f, 0x53,
	0xfe, 0x3b, 0x33, 0xa9, 0x7c, 0xe5, 0x4c, 0xfa, 0x02, 0xaa, 0xc9, 0x6b, 0xa8, 0x02, 0x45, 0xab,
	0xd3, 0x91, 0xb8, 0xec, 0xf5, 0xba, 0x07, 0xed, 0x43, 0x43, 0x41, 0x3a, 0x94, 0xfa, 0x03, 0x8e,
	0x84, 0x8a, 0xd6, 0xa0, 0xd6, 0x3b, 0xb1, 0xb1, 0x35, 0x68, 0xf7, 0xba, 0x56, 0xc7, 0x28, 0x9a,
	0x67, 0x50, 0x3b, 0xcc, 0xd5, 0xe1, 0x53, 0xa8, 0x7b, 0xb9, 0xad, 0x14, 0xb7, 0xd9, 0x25, 0xfb,
	0x0a, 0x2f, 0xc8, 0xf1, 0xbe, 0x94, 0xcb, 0x48, 0x5d, 0xce, 0xb9, 0xe4, 0x98, 0x37, 0x60, 0x7d,
	0x8f, 0x04, 0x64, 0xe4, 0xb8, 0x4e, 0x74, 0x11, 0xc3, 0x64, 0xfe, 0xa9, 0x00, 0xca, 0x53, 0x63,
	0x37, 0x9e, 0x81, 0xc1, 0xc7, 0x93, 0x1f, 0x46, 0x74, 0x92, 0x00, 0xa1, 0x5c, 0x0e, 0xc4, 0x5a,
	0x2a, 0x28, 0xe1, 0x40, 0x2f, 0xe0, 0x46, 0xa6, 0x9b, 0x80, 0xca, 0x44, 0x22, 0x97, 0x51, 0x47,
	0xa9, 0x68, 0x42, 0x62, 0xe8, 0x2e, 0xd4, 0xa7, 0xdd, 0xe3, 0xf6, 0xf0, 0x9c, 0x86, 0x8c, 0x63,
	0x20, 0x3f, 0x02, 0x6b, 0x9c, 0xf6, 0x5a, 0x92, 0xcc, 0xef, 0x40, 0x4f, 0x3d, 0xe0, 0x9f, 0x3e,
	0x1e, 0x99, 0xc9, 0xdd, 0xae, 0x63, 0x71, 0x46, 0x26, 0xd4, 0xfd, 0x70, 0x4a, 0x3c, 0xe7, 0x27,
	0x12, 0xaf, 0x4c, 0xce, 0x5b, 0xa0, 0xf1, 0x89, 0xb9, 0xf8, 0x44, 0x72, 0xdd, 0xde, 0x87, 0x6a,
	0xe2, 0x0e, 0xdf, 0x29, 0x5f, 0xf5, 0x7b, 0x5d, 0xa3, 0xc0, 0xd3, 0xb8, 0xfb, 0xed, 0xc0, 0xee,
	0xcb, 0x8c, 0x9e, 0xe0, 0xde, 0xa0, 0x67, 0xa8, 0x68, 0x05, 0x74, 0xce, 0x1f, 0xb6, 0xed, 0xc1,
	0x81, 0x51, 0xe4, 0x1c, 0xab, 0xbf, 0xd7, 0x6e, 0x1b, 0xda, 0xb6, 0xb5, 0xb8, 0xee, 0xc5, 0xde,
	0x42, 0xb0, 0x3a, 0xb0, 0xf0, 0xa1, 0x3d, 0x18, 0xee, 0xdb, 0x07, 0xed, 0xae, 0xcd, 0x5b, 0x68,
	0x05, 0xf4, 0x5e, 0x77, 0xb8, 0x77, 0x64, 0x75, 0x0f, 0x79, 0x17, 0xf1, 0xd5, 0x66, 0x1d, 0x9f,
	0x74, 0x6c, 0x43, 0xdd, 0xf9, 0x57, 0x01, 0x8d, 0xc7, 0x8d, 0x2c, 0xa8, 0xa7, 0x69, 0x72, 0x28,
	0x43, 0xb7, 0x25, 0x8e, 0x4b, 0x09, 0xdd, 0x68, 0x2c, 0x33, 0xe2, 0x9c, 0x6e, 0x43, 0xf1, 0x90,
	0x46, 0xc8, 0x78, 0xb7, 0x55, 0x36, 0xd6, 0x73, 0x94, 0x4c, 0xb6, 0x9f, 0xc9, 0xf6, 0x97, 0x64,
	0xf3, 0xa3, 0xf3, 0x25, 0xe8, 0xe9, 0x17, 0x17, 0x5a, 0x5c, 0x9c, 0xe9, 0x17, 0xe3, 0xc6, 0xed,
	0x25, 0xba, 0xd4, 0xde, 0x52, 0x1e, 0x2b, 0xcf, 0x5e, 0x42, 0x9d, 0x73, 0x87, 0x8c, 0x86, 0xe7,
	0xce, 0x98, 0xa2, 0x3b, 0x4b, 0xdf, 0xa3, 0x07, 0x8e, 0x4b, 0x7b, 0x02, 0x45, 0xd6, 0x78, 0x5b,
	0x89, 0xeb, 0xc1, 0x9b, 0x39, 0x7d, 0xa9, 0xb1, 0x5b, 0xfd, 0xeb, 0xcb, 0xd2, 0xe3, 0xe6, 0x4e,
	0xf3, 0xf1, 0xa8, 0x2c, 0x74, 0x9e, 0xfc, 0x17, 0x00, 0x00, 0xff, 0xff, 0xfb, 0xf7, 0xf9, 0x22,
	0x43, 0x0d, 0x00, 0x00,
}
